spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: 4v8y/B?E(H+MbQeThWmZq4t7w!z%C*F-JaNdRgUkXp2s5v8y
  expiration: 86400000

server:
  port: 8080